version: "3.9"

services:
    async-consumer:
        image: nissaya98/main-php:8.1-fpm-alpine-dev
        command: php /var/www/html/akvarel/bin/console messenger:consume async --limit=1000 --time-limit=600
        hostname: async-consumer-{.Node.Hostname}}-{{.Task.Slot}}
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        volumes:
            -   type: bind
                source: ../config/php-fpm/local.ini
                target: /usr/local/etc/php/conf.d/local.ini
            -   type: bind
                source: ../core
                target: /var/www/html
            -   type: bind
                source: ../var/workers/async-consumer
                target: /var/log/async-consumer
            -   type: bind
                source: ../var/storage/upload
                target: /var/upload
        networks:
            - demosite
networks:
    demosite:
        external: true