framework:
    messenger:
        default_bus: async.bus
        buses:
            async.bus:
                middleware:
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection

                    # After handling, the Doctrine connection is closed,
                    # which can free up database connections in a worker,
                    # instead of keeping them open forever
                    - doctrine_close_connection
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 1
                    multiplier: 10
                options:
                    exchange:
                        name: async
                    queues:
                        async: ~


            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            failed: '%env(MESSENGER_FAILED_DSN)%'

        routing:
            # Route your messages to the transports
#            App\Model\MessageBus\Message\Email\SendEmailMessage: email
